const imagePaths = [
    "https://tiwut.de/Deutsch/My Projects/AI_Terminal_Self-learning.jpg",
    "https://tiwut.de/Deutsch/My Projects/Block Blast Klon.jpg",
    "https://tiwut.de/Deutsch/My Projects/Clash Royale Clone.jpg",
    "https://tiwut.de/Deutsch/My Projects/Image Converter PNG-JPG-ICO.jpg",
    "https://tiwut.de/Deutsch/My Projects/Image Editor.jpg",
    "https://tiwut.de/Deutsch/My Projects/PNG-JPG-Resize.jpg",
    "https://tiwut.de/Deutsch/My Projects/Subway Runner.jpg",
    "https://tiwut.de/Deutsch/My Projects/Text Editor.jpg",
    "https://tiwut.de/English/My Projects/AI_Terminal_Self-learning.jpg",
    "https://tiwut.de/English/My Projects/Block Blast Klon.jpg",
    "https://tiwut.de/English/My Projects/Clash Royale Clone.jpg",
    "https://tiwut.de/English/My Projects/Image Converter PNG-JPG-ICO.jpg",
    "https://tiwut.de/English/My Projects/Image Editor.jpg",
    "https://tiwut.de/English/My Projects/PNG-JPG-Resize.jpg",
    "https://tiwut.de/English/My Projects/Subway Runner.jpg",
    "https://tiwut.de/English/My Projects/Text Editor.jpg",
    "https://tiwut.de/Espanol/My Projects/AI_Terminal_Self-learning.jpg",
    "https://tiwut.de/Espanol/My Projects/Block Blast Klon.jpg",
    "https://tiwut.de/Espanol/My Projects/Clash Royale Clone.jpg",
    "https://tiwut.de/Espanol/My Projects/Image Converter PNG-JPG-ICO.jpg",
    "https://tiwut.de/Espanol/My Projects/Image Editor.jpg",
    "https://tiwut.de/Espanol/My Projects/PNG-JPG-Resize.jpg",
    "https://tiwut.de/Espanol/My Projects/Subway Runner.jpg",
    "https://tiwut.de/Espanol/My Projects/Text Editor.jpg",
    "https://tiwut.de/Guides/Unity Tutorial/placeholder_install_modules.png",
    "https://tiwut.de/Guides/Unity Tutorial/placeholder_unity_editor.png",
    "https://tiwut.de/NEWS/media/MacOS_DualBoot.png",
    "https://tiwut.de/NEWS/media/new domain.png",
    "https://tiwut.de/Tools/3d-model-store/Game_Animals_Character_Asset_V1.1/Game_Animals_Character_Asset_V1.1.png",
    "https://tiwut.de/Tools/3d-model-store/Game_Character_Asset_V1.1/Game_Character_Asset_V1.1.png",
    "https://tiwut.de/Tools/3d-model-store/Game_Character_Asset_V1.2/Game_Character_Asset_V1.2.png",
    "https://tiwut.de/Tools/3d-model-store/Tree_Asset_Large/Tree_Asset_Large.png",
    "https://tiwut.de/Tools/3d-model-store/Tree_Asset_Large_Tall_V1.2/Game_Animals_Character_Asset_V1.1/Game_Animals_Character_Asset_V1.1.png",
    "https://tiwut.de/Tools/3d-model-store/Tree_Asset_Large_Tall_V1.2/Game_Animals_Character_Asset_V1.1/main.jpg",
    "https://tiwut.de/Tools/3d-model-store/Tree_Asset_Large_Tall_V1.2/Tree_Asset_Large_Tall_V1.2_fbx.png",
    "https://tiwut.de/Tools/3d-model-store/Tree_Asset_Large_Tall_V1.2/Tree_Asset_Large_Tall_V1.2_obj.png",
    "https://tiwut.de/Tools/3d-model-store/Tree_Asset_Large_V1.2/Tree_Asset_Large_V1.2.png",
    "https://tiwut.de/Tools/Roadtrip Planer/v1.1/main.png"
];